services:
    php:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                - "PHP_VERSION=${PHP_VERSION}"
        container_name: tasks_api_php
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - tasks_api_net

    nginx:
        image: nginx:alpine
        container_name: tasks_api_nginx
        restart: unless-stopped
        depends_on:
            - php
        environment:
            - NGINX_ENTRYPOINT_QUIET_LOGS=1
            - NGINX_SERVER_NAME=laravel-api.com
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - tasks_api_net

    mysql:
        image: "mysql:${MYSQL_VERSION}"
        platform: linux/amd64
        container_name: tasks_api_mysql
        restart: always
        ports:
            - "${APP_DB_PORT}:3306"
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/config:/etc/mysql/conf.d
        environment:
            MYSQL_USER : ${DB_USERNAME}
            MYSQL_PASSWORD : ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD : ${DB_ROOT_PASSWORD}
        expose:
            - "${APP_DB_PORT}"
        networks:
            - tasks_api_net

    redis:
        image: redis:latest
        container_name: tasks_api_redis
        restart: always
        ports:
            - "${APP_REDIS_PORT}:6379"
        volumes:
            - ./docker/redis/d–∞ta:/data
            - ./docker/redis/config:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_DATABASES=${REDIS_DB}
        networks:
            - tasks_api_net

networks:
    tasks_api_net:
        name: tasks_api_net
        driver: bridge
